app:
 name: sso

server:
  port: 8081

nacos:
  server_ip: localhost
  server_port: 8848
  namespace: f30e57f3-64f5-40a9-9eae-3db86d3938ac
  group: DEFAULT_GROUP
  data_id: patato-sso.yaml
  auth:
    enabled: false
