app:
 name: sso

server:
  port: 8081

nacos:
  server_ip: localhost
  server_port: 8848
  namespace: aa710a50-3c1e-4581-9107-11bd8a4502cd
  group: DEFAULT_GROUP
  data_id: patato-sso.yaml
  ephemeral: true
  auth:
    enabled: false
